import threading
import smtplib
import time 
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText 
number_of_emails_sent = 0 
n = int(0) 
mail_content = 'have fun'
sender_address = "python.bot.spam@outlook.com"
sender_pass = '34wutl76tierbgsdfvdafwdawd'
receiver_address = input("enter the email adress of the person who is going to recive the spam:""" )
def ThFun(start, stop):
    for item in range(start, stop):
        print (item)  

for i in range(n):
  mail_content = 'have fun' 
  sender_address = "python.bot.spam@outlook.com"
  sender_pass = '5U5ZU$CtPWxUF*r+'
  message = MIMEMultipart()
  message['From'] = sender_address
  message['To'] = receiver_address
  message['Subject'] = 'Python spam mail'   
  message.attach(MIMEText(mail_content, 'plain'))
  session = smtplib.SMTP('smtp-mail.outlook.com', 587)
  session.starttls()
  session.login(sender_address, sender_pass)
  text = message.as_string() 
  session.sendmail(sender_address, receiver_address, text)
  session.quit() 
  number_of_emails_sent += 1 ; 

for n in range(0, 1000, 100):
    stop = n + 100 if n + 100 <= 1000 else 1000 ;

threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start() 
threading.Thread(target = ThFun, args = (n, stop)).start()  
print("finished")